# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joiningtask',
            name='dateOfJoining',
            field=models.DateField(null=True, verbose_name=b'date set'),
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='customersInvolved',
            field=models.ManyToManyField(null=True, through='tasks.joiningTask', to='tasks.customer'),
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='taskDate',
            field=models.DateField(null=True, verbose_name=b'date set'),
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='taskTime',
            field=models.TimeField(null=True, verbose_name=b'time set'),
        ),
    ]
