# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180610_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_id',
            field=models.CharField(max_length=600),
        ),
    ]
