# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180619_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='joiningtask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
