# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180630_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='customersInvolved',
            field=models.ManyToManyField(through='tasks.joiningTask', to='tasks.customer'),
        ),
    ]
