# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20180701_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='isAlarmTrue',
            field=models.BooleanField(default=False),
        ),
    ]
